### DISCUSSION TITLE
Remove dropdown on certain buttons

### DISCUSSION THREAD

**Discussion by trymeouteh** [xdan/jodit#974] [Q&A] [answered]
For the following buttons, it has a dropdown option to select more options. Is there a way to remove or change these dropdown options?

- OL
- UL
- Paste
- Align
- Font
- Font Size
- Paragraph
- Line Spacing
- Class Span

**Comment by mrothauer** [comment]
I wanted to ged rid of the options in UL completely. The only solution I found was reducing the options to the default option

```
Jodit.make('#editor', {
  controls: {
      ul: {
          list: Jodit.atom({
              default: 'Default',
          })
      },
  }, 
 buttons: ['bold', 'italic', 'ul'],
});
```

Details
https://github.com/foodcoopshop/foodcoopshop/blob/231c47b2f3d8d017b8010b0407514c64a76a7d8b/plugins/Admin/webroot/js/editor.js#L20

**Reply by trymeouteh** [reply]
I am unable to find an way to modify the following dropdown options...

- ordered lists (cannot change options)
- classSpan (add class names with dash in them "text-center", "text-left")
- align (change display name/icon, change options)
- find

However I was able to figure out how to edit the other dropdown options using the code you provided.

**Comment by kahunacoder** [comment]
I used css to remove the redundant arrows I didn't want like so. Notice the `*` match any `^` match beginning and the `i` at the end to ignore case.

```css
<style>
	[aria-label*="Align" i] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label^="Font"] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label*="Insert" i] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label="Line height"] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label*="split" i] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label="Background"] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label^="Fill"] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
	[aria-label^="Paste"] .jodit-toolbar-button__trigger{
		display: none  !important;
	}
</style>
```
You can do this in the controls to change options 

```js
Jodit.make('#editor', {
  controls: {
		paragraph: {
			list: Jodit.atom({
					p: 'Normal',
					h2: 'Heading 2',
					h3: 'Heading 3',
			}),
  }, 
```
