### ISSUE TITLE
Filebrowser - image preview has wrong classes

### ISSUE THREAD

**Issue by marcinskubala** [xdan/jodit#279]
**Jodit Version:**  3.2.56

**Browser:**  All
**OS:**  Windows 10

**Problem**
Clicking on image preview generate wrong html. Check below code.

**Expected behavior:**
```html
<div class="jodit_filebrowser_preview">
   <a href="javascript:void(0)" class="jodit_filebrowser_preview_navigation jodit_filebrowser_preview_navigation-prev">...</a>
   <div class="jodit_filebrowser_preview_box">...</div>
</div>
```

**Actual behavior:**
```html
<div class="jodit_filebrowser_preview">
   <a href="javascript:void(0)" class="undefinedpreview_navigation undefinedpreview_navigation-prev">...</a>
   <div class="jodit_filebrowserpreview_box">...</div>
</div>
```

For now I "fixed" it by adding custom css:
```css
.jodit_filebrowserpreview{text-align:center;min-width:600px;max-width:1000px;min-height:700px;max-height:100%;position:relative}
.jodit_filebrowserpreview{display:-ms-flexbox;display:flex;-ms-flex-pack:center;justify-content:center;-ms-flex-align:center}
.jodit_filebrowserpreview img{max-width:100%;max-height:100%}

.undefinedpreview_navigation{position:absolute;top:0;height:100%;left:0}
.undefinedpreview_navigation-next{left:auto;right:0}
.undefinedpreview_navigation svg{width:45px;height:45px;position:relative;top:50%;margin-top:-22px;transition:fill .3s linear;fill:#9e9ba7}
.undefinedpreview_navigation:hover svg{fill:#000}
```
