### ISSUE TITLE
Toolbar tooltip behaviour after page scroll down

### ISSUE THREAD

**Issue by idhamperdameian** [xdan/jodit#76]
**Jodit Version:**  v3.2.9
Toolbar tooltip is not in it place after i scroll down the page. 

**Code**
This is the fixed css i use.

```css
.jodit_tooltip {
    position: absolute;
    ....
}
```

Css before:
```css
.jodit_tooltip {
    position: fixed;
    ....
}
```

**Expected behavior:**
See image below. After scroll page down, toolbar  tooltip should in it place

![image](https://user-images.githubusercontent.com/3077042/43457678-cbe22c46-94f1-11e8-8039-ff973c8389ed.png)

**Actual behavior:**
See image below.

![image](https://user-images.githubusercontent.com/3077042/43457511-48d15e3a-94f1-11e8-84b6-faf3e74666bd.png)
