### ISSUE TITLE
No changes after clicking Insert Format Block icon and  Insert Class Name icon for copy paste content

### ISSUE THREAD

**Issue by marygrace1235** [xdan/jodit#800]
**Jodit Version:**  3.4.xxxxx

**Browser:**  Chrome
**OS:**  Windows
**Is React App:**  True

Copy paste the content from word,select a word and Click any drop down option from Insert Format Block and Insert Class Name.
No changes are reflecting after selecting and clicking Insert format Block icon  and  Insert Class Name icon

**Expected behavior:**
![image](https://user-images.githubusercontent.com/90672801/157207004-208a1ca7-fc30-4fb9-8ae6-6d5c1b396822.png)
![image](https://user-images.githubusercontent.com/90672801/157207074-eb209b1a-4e4e-4547-914c-ade38c7894d1.png)

**Actual behavior:**
No changes after selecting the text and clicking Insert Format block and insert class Name

**Comment by masechkacat** [comment]
I encountered a similar issue when using Jodit with React and Tailwind CSS. The problem occurs because Tailwind's preflight CSS reset removes default HTML element styles.

**Solution:**

Add these styles to restore default HTML formatting:

```css
.jodit h1,
.jodit h2,
.jodit h3,
.jodit h4,
.jodit pre {
  all: revert; /* This restores default browser styles */
}

/* Optional: You can also add custom styles for blockquotes */
.jodit blockquote {
  font-style: italic;
  padding: 1rem 1rem 1rem 2rem;
  margin: 1rem 0;
  border-left: 4px solid #e5e7eb;
  background-color: #f9fafb;
  position: relative;
  color: #4b5563;
}
```
Alternatively, you can disable Tailwind's preflight in your `tailwind.config.js` :

```js
module.exports = {
  corePlugins: {
    preflight: false,
  }
}
```
This should restore the proper formatting for Insert Format Block options (headings, blockquotes, etc.) in the Jodit editor. #
